<?php 

# An array containing the parameters of the update query issued when modifying a client. This array
# follows the order of the fields in the array in 'modclient/query.php'.
# Input : every variable in the array
# Output: $query_prm

$query_prm = [
    $dossier,
    $loyalty_start,
    $use_loyalty_points,
    $loyaltydate, 
    $isclient,
    $isemployee,
    $isother,
    $clientcode,
    $clienthistory,
    $contact2,
    $contact3,
    $surcharge,
    $countryid,
    $employee2id,
    $clientsectorid,
    $clerib,
    $guichet,
    $codebanque,
    $domi,
    $titu,
    $usedetail,
    $discount,
    $quarter,
    $postaladdress,
    $outstandinglimit,
    $companytypename,
    $postalcode,
    $employeeid,
    $blocked,
    $account,
    $vatexempt,
    $address,
    $townid,
    $contact,
    $fax,
    $clientcategoryid,
    $clientcategory2id,
    $clientcategory3id,
    $bankreference,
    $clienttermid,
    $surcharge,
    $tahitinumber,
    $rc,
    $comment,
    $creationdate,
    $clientfirstname,
    $clientfield1,
    $clientfield2,
    $clientfield3,
    $clientfield4,
    $clientfield5,
    $clientfield6,
    $client_customdate1,
    $client_customdate2,
    $client_customdate3,
    $town_name
];