<?php 

# An array containing the fields that should be included in the update query when modifying a 
# client.
# Input : no input
# Output: $query_vars

$query_vars = [
    'dossier',
    'loyalty_start',
    'use_loyalty_points',
    'loyaltydate',
    'isclient',
    'isemployee',
    'isother',
    'clientcode',
    'clienthistory',
    'contact2',
    'contact3',
    'surcharge',
    'countryid',
    'employeeid2',
    'clientsectorid',
    'clerib',
    'guichet',
    'codebanque',
    'domi',
    'titu',
    'usedetail',
    'discount',
    'quarter',
    'postaladdress',
    'outstandinglimit',
    'companytypename',
    'postalcode',
    'employeeid',
    'blocked',
    'account',
    'vatexempt',
    'address',
    'townid',
    'contact',
    'fax',
    'clientcategoryid',
    'clientcategory2id',
    'clientcategory3id',
    'bankreference',
    'clienttermid',
    'surcharge',
    'tahitinumber',
    'rc',
    'clientcomment',
    'creationdate',
    'clientfirstname',
    'clientfield1',
    'clientfield2',
    'clientfield3',
    'clientfield4',
    'clientfield5',
    'clientfield6',
    'client_customdate1',
    'client_customdate2',
    'client_customdate3',
    'town_name'
    ];